version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: midcart-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: smartpharma

  backend:
    build: ./server
    container_name: midcart-backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/smartpharma
      - JWT_SECRET=supersecretjwtkey123
      - NODE_ENV=development
      - CLIENT_URL=http://localhost:5173
    depends_on:
      - mongodb
    volumes:
      - ./server:/app
      - /app/node_modules

  frontend:
    build: ./client
    container_name: midcart-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=https://midcart-backend.onrender.com
    depends_on:
      - backend

volumes:
  mongo_data: