/**
 * Product catalog for seeding. Images: Pexels (free use — see https://www.pexels.com/license/)
 */
const px = (id) =>
  `https://images.pexels.com/photos/${id}/pexels-photo-${id}.jpeg?auto=compress&cs=tinysrgb&w=720&h=720&dpr=1`;

/** Default strip image used when admin creates a product without photos */
const DEFAULT_PRODUCT_PHOTO = 4031818;

const products = [
  {
    name: 'Paracetamol 500mg',
    genericName: 'Paracetamol',
    brand: 'Calpol',
    description: 'Effective pain and fever relief tablet',
    category: 'fever-cold',
    price: { mrp: 30, selling: 25, discount: 17 },
    stock: { quantity: 500, unit: 'strip', lowStockThreshold: 20 },
    expiryDate: new Date('2026-12-01'),
    requiresPrescription: false,
    manufacturer: 'GSK',
    composition: 'Paracetamol IP 500mg',
    dosage: '1-2 tablets every 4-6 hours',
    tags: ['fever', 'pain', 'headache'],
    isFeatured: true,
    salesCount: 320,
    images: [{ url: '/uploads/products/1.jpg', public_id: 'local' }],
  },
  {
    name: 'Metformin 500mg',
    genericName: 'Metformin HCl',
    brand: 'Glycomet',
    description: 'Oral anti-diabetic medication',
    category: 'diabetes',
    price: { mrp: 85, selling: 70, discount: 18 },
    stock: { quantity: 200, unit: 'strip', lowStockThreshold: 15 },
    expiryDate: new Date('2026-08-01'),
    requiresPrescription: true,
    manufacturer: 'USV',
    composition: 'Metformin Hydrochloride IP 500mg',
    dosage: 'As prescribed by doctor',
    tags: ['diabetes', 'blood sugar'],
    isFeatured: true,
    salesCount: 180,
    images: [{ url: '/uploads/products/2.webp', public_id: 'local' }],
  },
  {
    name: 'Vitamin C 1000mg',
    genericName: 'Ascorbic Acid',
    brand: 'Limcee',
    description: 'Immunity booster vitamin supplement',
    category: 'vitamins',
    price: { mrp: 120, selling: 99, discount: 18 },
    stock: { quantity: 350, unit: 'strip', lowStockThreshold: 25 },
    expiryDate: new Date('2027-03-01'),
    requiresPrescription: false,
    manufacturer: 'Abbott',
    composition: 'Ascorbic Acid 1000mg',
    dosage: '1 tablet daily',
    tags: ['immunity', 'vitamin', 'supplement'],
    isFeatured: true,
    salesCount: 290,
    images: [{ url: '/uploads/products/3.jpg', public_id: 'local' }],
  },
  {
    name: 'Atorvastatin 10mg',
    genericName: 'Atorvastatin Calcium',
    brand: 'Lipitor',
    description: 'Cholesterol-lowering medication',
    category: 'heart',
    price: { mrp: 150, selling: 120, discount: 20 },
    stock: { quantity: 8, unit: 'strip', lowStockThreshold: 10 },
    expiryDate: new Date('2025-06-01'),
    requiresPrescription: true,
    manufacturer: 'Pfizer',
    composition: 'Atorvastatin Calcium 10mg',
    dosage: 'As prescribed by doctor',
    tags: ['cholesterol', 'heart', 'statin'],
    isFeatured: false,
    salesCount: 95,
    images: [{ url: '/uploads/products/4.webp', public_id: 'local' }],
  },
  {
    name: 'Cetirizine 10mg',
    genericName: 'Cetirizine Hydrochloride',
    brand: 'Zyrtec',
    description: 'Anti-allergic and antihistamine tablet',
    category: 'fever-cold',
    price: { mrp: 45, selling: 38, discount: 16 },
    stock: { quantity: 400, unit: 'strip', lowStockThreshold: 20 },
    expiryDate: new Date('2026-10-01'),
    requiresPrescription: false,
    manufacturer: 'UCB',
    composition: 'Cetirizine HCl 10mg',
    dosage: '1 tablet daily at night',
    tags: ['allergy', 'cold', 'antihistamine'],
    isFeatured: false,
    salesCount: 210,
    images: [{ url: '/uploads/products/5.jpg', public_id: 'local' }],
  },
  {
    name: 'Omeprazole 20mg',
    genericName: 'Omeprazole',
    brand: 'Omez',
    description: 'Proton pump inhibitor for acidity',
    category: 'digestive',
    price: { mrp: 60, selling: 48, discount: 20 },
    stock: { quantity: 300, unit: 'strip', lowStockThreshold: 15 },
    expiryDate: new Date('2026-09-01'),
    requiresPrescription: false,
    manufacturer: "Dr. Reddy's",
    composition: 'Omeprazole IP 20mg',
    dosage: '1 capsule before meal',
    tags: ['acidity', 'gastric', 'heartburn'],
    isFeatured: true,
    salesCount: 175,
    images: [{ url: '/uploads/products/6.jpg', public_id: 'local' }],
  },
  {
    name: 'Azithromycin 500mg',
    genericName: 'Azithromycin',
    brand: 'Azithral',
    description: 'Macrolide antibiotic for bacterial infections',
    category: 'antibiotics',
    price: { mrp: 120, selling: 95, discount: 21 },
    stock: { quantity: 180, unit: 'strip', lowStockThreshold: 15 },
    expiryDate: new Date('2026-11-01'),
    requiresPrescription: true,
    manufacturer: 'Alembic',
    composition: 'Azithromycin IP 500mg',
    dosage: 'As prescribed by doctor',
    tags: ['antibiotic', 'infection', 'bacterial'],
    isFeatured: true,
    salesCount: 140,
    images: [{ url: '/uploads/products/7.jpg', public_id: 'local' }],
  },
  {
    name: 'Ibuprofen 400mg',
    genericName: 'Ibuprofen',
    brand: 'Brufen',
    description: 'NSAID for pain and inflammation',
    category: 'pain-relief',
    price: { mrp: 55, selling: 42, discount: 24 },
    stock: { quantity: 420, unit: 'strip', lowStockThreshold: 25 },
    expiryDate: new Date('2027-01-01'),
    requiresPrescription: false,
    manufacturer: 'Abbott',
    composition: 'Ibuprofen IP 400mg',
    dosage: '1 tablet after food as needed',
    tags: ['pain', 'inflammation', 'fever'],
    isFeatured: true,
    salesCount: 260,
    images: [{ url: '/uploads/products/8.webp', public_id: 'local' }],
  },
  {
    name: 'Clotrimazole 1% Cream',
    genericName: 'Clotrimazole',
    brand: 'Candid',
    description: 'Antifungal cream for skin infections',
    category: 'skin',
    price: { mrp: 95, selling: 78, discount: 18 },
    stock: { quantity: 220, unit: 'tube', lowStockThreshold: 12 },
    expiryDate: new Date('2026-12-15'),
    requiresPrescription: false,
    manufacturer: 'Glenmark',
    composition: 'Clotrimazole 1% w/w',
    dosage: 'Apply thin layer twice daily',
    tags: ['antifungal', 'skin', 'rash'],
    isFeatured: false,
    salesCount: 88,
    images: [{ url: '/uploads/products/9.jpeg', public_id: 'local' }],
  },
  {
    name: 'Ciprofloxacin Eye Drops',
    genericName: 'Ciprofloxacin',
    brand: 'Ciplox',
    description: 'Antibiotic eye drops for bacterial conjunctivitis',
    category: 'eye-ear',
    price: { mrp: 72, selling: 59, discount: 18 },
    stock: { quantity: 150, unit: 'bottle', lowStockThreshold: 10 },
    expiryDate: new Date('2026-07-01'),
    requiresPrescription: true,
    manufacturer: 'Cipla',
    composition: 'Ciprofloxacin 0.3%',
    dosage: '1-2 drops in affected eye as directed',
    tags: ['eye', 'infection', 'drops'],
    isFeatured: false,
    salesCount: 62,
    images: [{ url: '/uploads/products/10.webp', public_id: 'local' }],
  },
];

module.exports = { products, DEFAULT_PRODUCT_PHOTO, productImageUrl: (id) => px(id) };
